services:
  - type: worker
    name: upload-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 upload_bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ALLOWED_USER
        sync: false
